name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['main']

env:
  HUSKY: 0

jobs:
  install:
    name: Install
    uses: ./.github/workflows/install.yml
    with:
      branch: ${{ github.head_ref }}

  prettier:
    name: Prettier
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run prettier
        run: npm run prettier

  lint:
    name: Lint codebase
    needs: [install]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run linter
        run: npm run lint

  tests:
    name: Run tests
    needs: [install, lint, prettier]
    uses: ./.github/workflows/tests.yml
    with:
      branch: ${{ github.head_ref }}

  dependabot:
    name: Check for Dependabot
    needs: [tests]
    uses: ./.github/workflows/dependabot.yml
    with:
      branch: ${{ github.head_ref }}

