name: Dependabot pull request

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  dependabot:
    runs-on: ubuntu-latest
    name: Merge patch PRs
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
    steps:
      - name: Get metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1

      - name: Merge pull requests (patch/minor)
        uses: pascalgn/automerge-action@v0.16.3
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor' }}
    